name: Build with Webpack

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Setup Node JS
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Build
      run: |
        npm install
        npm run all
    - uses: EndBug/add-and-commit@v9
      name: Commit changed build
      with:
        message: Build changed
        fetch: false
        push: true
